services:
  traefik:
    image: traefik:v3.7.5
    security_opt:
      - label=disable # for SELinux
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--entrypoints.web.address=:80"
    ports:
      - "8888:80"   # Apache
      - "8080:8080" # Traefik Dashboard
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"

  app:
    build:
      context: .
      dockerfile: docker/Dockerfile
      target: ${BUILD_TARGET:-base}
    labels:
      - "traefik.http.routers.app.rule=PathPrefix(`/`)"
